"""
FastAPI application factory and startup/shutdown handlers.
"""

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.router import router
from app.config import settings
from app.db import engine, async_session_maker
from app.db.base import Base
from app.demo_data import seed_database
from app.rag.indexer import index_policy_documents

# Configure logging
logging.basicConfig(
    level=getattr(logging, settings.log_level),
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)

logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Lifespan context manager for startup and shutdown tasks.
    
    Startup:
    - Create database tables (via Alembic in production)
    - Seed synthetic data if configured
    - Index policy documents for RAG
    
    Shutdown:
    - Close database connections
    """
    logger.info("Starting up Enterprise Agentic Workflow Engine...")
    
    # Create tables (in production, use Alembic migrations)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    logger.info("Database tables initialized")
    
    # Seed database if configured
    if settings.seed_on_startup:
        try:
            async with async_session_maker() as session:
                seed_result = await seed_database(session)
                logger.info(f"Database seeding completed: {seed_result}")
                
                # Index policy documents
                if seed_result.get("policies", 0) > 0:
                    indexed_count = await index_policy_documents(session)
                    logger.info(f"Indexed {indexed_count} policy documents")
        except Exception as e:
            logger.error(f"Seeding failed: {e}")
    
    logger.info("Application startup complete")
    
    yield
    
    # Shutdown
    logger.info("Shutting down Enterprise Agentic Workflow Engine...")
    await engine.dispose()
    logger.info("Database connections closed")


def create_app() -> FastAPI:
    """
    Create and configure the FastAPI application.
    
    Returns:
        Configured FastAPI application instance
    """
    app = FastAPI(
        title=settings.app_name,
        version=settings.app_version,
        description="""
        # Enterprise Agentic Workflow Engine (Finance Demo)
        
        **⚠️ IMPORTANT DISCLAIMER ⚠️**
        
        This is a **DEMONSTRATION PROJECT** for educational and portfolio purposes only.
        
        - All data is **SYNTHETIC** and generated by the Faker library
        - No real customer information is used or stored
        - No real financial institutions are referenced
        - Not intended for production use or with real customer data
        - All policies and procedures are fictional
        
        ## What This Demonstrates
        
        This project showcases production-grade backend engineering patterns:
        
        - **LangGraph**: State machine orchestration with conditional routing
        - **RAG**: Retrieval-Augmented Generation using PostgreSQL + pgvector
        - **Guardrails**: Tool allowlisting, schema validation, content filtering
        - **Audit Logging**: Append-only event tracking for all operations
        - **Pydantic Validation**: Strict input/output schema enforcement
        - **Async Architecture**: Full async/await with SQLAlchemy 2.0
        - **Docker Deployment**: Containerized setup with docker-compose
        
        ## Architecture
        
        The workflow executes these steps:
        
        1. **Ingest Transactions**: Analyze customer transaction history
        2. **Detect Anomalies**: Identify suspicious patterns using heuristics
        3. **Retrieve Policies**: RAG-based policy document retrieval
        4. **Draft Explanation**: Generate natural language analysis
        5. **Evaluate Confidence**: Determine if human escalation is needed
        6. **Escalate/Finalize**: Route to appropriate conclusion
        
        All steps are logged to an immutable audit trail.
        """,
        lifespan=lifespan,
        debug=settings.debug,
    )
    
    # Add CORS middleware
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],  # Configure appropriately for production
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )
    
    # Include router
    app.include_router(router, prefix="/api/v1", tags=["workflow"])
    
    @app.get("/")
    async def root():
        """Root endpoint with project information."""
        return {
            "project": settings.app_name,
            "version": settings.app_version,
            "description": "Enterprise Agentic Workflow Engine - Demo Project",
            "disclaimer": "This is a demo project with synthetic data only. Not for production use.",
            "docs": "/docs",
            "health": "/api/v1/health",
        }
    
    return app


# Create application instance
app = create_app()


if __name__ == "__main__":
    import uvicorn
    
    uvicorn.run(
        "app.main:app",
        host=settings.host,
        port=settings.port,
        reload=settings.debug,
        log_level=settings.log_level.lower(),
    )
